Repository KUSITMS-MOAMOA/MOAMOA_BE, pull requests merged in 2024-11, with the labels that each got.

#38 [Feat/#37] 경험 기록 폴더 위치 변경 기능 구현
  src/main/java/corecord/dev/domain/record/constant/RecordSuccessStatus.java
  src/main/java/corecord/dev/domain/record/controller/RecordController.java
  src/main/java/corecord/dev/domain/record/dto/request/RecordRequest.java
  src/main/java/corecord/dev/domain/record/entity/Record.java
  src/main/java/corecord/dev/domain/record/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Feat 💙

#41 [Feat/#34] 경험 기록하기 채팅 구현
  .gitignore
  build.gradle
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/common/util/ResourceLoader.java
  src/main/java/corecord/dev/domain/chat/constant/ChatSuccessStatus.java
  src/main/java/corecord/dev/domain/chat/controller/ChatController.java
  src/main/java/corecord/dev/domain/chat/converter/ChatConverter.java
  src/main/java/corecord/dev/domain/chat/dto/request/ChatRequest.java
  src/main/java/corecord/dev/domain/chat/dto/request/ClovaRequest.java
  src/main/java/corecord/dev/domain/chat/dto/response/ChatResponse.java
  src/main/java/corecord/dev/domain/chat/entity/ChatRoom.java
  src/main/java/corecord/dev/domain/chat/exception/enums/ChatErrorStatus.java
  src/main/java/corecord/dev/domain/chat/exception/model/ChatException.java
  src/main/java/corecord/dev/domain/chat/repository/ChatRepository.java
  src/main/java/corecord/dev/domain/chat/repository/ChatRoomRepository.java
  src/main/java/corecord/dev/domain/chat/service/ChatService.java
  src/main/java/corecord/dev/domain/chat/service/ClovaService.java
  src/main/java/corecord/dev/domain/user/entity/User.java
Labels: Feat 💙

#42 [Chore/#40] 역량 분석 레포트 Content 수정
  src/main/java/corecord/dev/domain/analysis/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/dto/request/AnalysisRequest.java
  src/main/java/corecord/dev/domain/analysis/entity/Ability.java
  src/main/java/corecord/dev/domain/analysis/entity/Analysis.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/record/dto/request/RecordRequest.java
  src/main/java/corecord/dev/domain/record/entity/Record.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Chore 🧹

#52 [Feat/#44] 채팅 경험 기록 임시 저장 기능 구현
  src/main/java/corecord/dev/domain/chat/constant/ChatSuccessStatus.java
  src/main/java/corecord/dev/domain/chat/controller/ChatController.java
  src/main/java/corecord/dev/domain/chat/converter/ChatConverter.java
  src/main/java/corecord/dev/domain/chat/dto/response/ChatResponse.java
  src/main/java/corecord/dev/domain/chat/exception/enums/ChatErrorStatus.java
  src/main/java/corecord/dev/domain/chat/service/ChatService.java
  src/main/java/corecord/dev/domain/user/entity/User.java
Labels: Feat 💙

#53 [Feat/#25] 역량 분석 기능 구현(2)
  .gitignore
  src/main/java/corecord/dev/common/status/ErrorStatus.java
  src/main/java/corecord/dev/common/util/ClovaRequest.java
  src/main/java/corecord/dev/common/util/ClovaService.java
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisAiResponse.java
  src/main/java/corecord/dev/domain/analysis/exception/enums/AnalysisErrorStatus.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/chat/service/ChatService.java
Labels: Feat 💙

#54 [Feat/#50] 역량 키워드 그래프 기능 구현
  src/main/java/corecord/dev/domain/analysis/constant/AnalysisSuccessStatus.java
  src/main/java/corecord/dev/domain/analysis/controller/AnalysisController.java
  src/main/java/corecord/dev/domain/analysis/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisResponse.java
  src/main/java/corecord/dev/domain/analysis/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
Labels: Feat 💙

#55 [Add/#39] : 역량분석 상세 조회 내역에 type, id 추가
  src/main/java/corecord/dev/domain/analysis/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisResponse.java
Labels: Add ✨

#57 [Refactor/#56] 최근 생성된 경험 기록 리스트 조회 기능 재구현
  src/main/java/corecord/dev/domain/record/constant/RecordSuccessStatus.java
  src/main/java/corecord/dev/domain/record/controller/RecordController.java
  src/main/java/corecord/dev/domain/record/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Refactor ♻️

#60 [Fix/#49] 채팅 + 메모 경험 기록하기 기능 구현
  src/main/java/corecord/dev/domain/record/constant/RecordSuccessStatus.java
  src/main/java/corecord/dev/domain/record/controller/RecordController.java
  src/main/java/corecord/dev/domain/record/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/dto/request/RecordRequest.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Fix 🛠️

#61 [Feat/#45] MEMO ver. 경험 기록 요약 기능 구현
  src/main/java/corecord/dev/common/util/ClovaRequest.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/record/entity/Record.java
Labels: Feat 💙

#63 [Feat/#62] 역량 분석 재요청 기능 구현
  src/main/java/corecord/dev/domain/analysis/constant/AnalysisSuccessStatus.java
  src/main/java/corecord/dev/domain/analysis/controller/AnalysisController.java
  src/main/java/corecord/dev/domain/analysis/entity/Analysis.java
  src/main/java/corecord/dev/domain/analysis/exception/enums/AnalysisErrorStatus.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
Labels: Feat 💙

#64 [Refactor/#58] 액세스 토큰 쿠키로 전달되게 수정
  src/main/java/corecord/dev/common/config/SecurityConfig.java
  src/main/java/corecord/dev/common/util/CookieUtil.java
  src/main/java/corecord/dev/common/util/JwtFilter.java
  src/main/java/corecord/dev/domain/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/corecord/dev/domain/token/controller/TokenController.java
  src/main/java/corecord/dev/domain/token/converter/TokenConverter.java
  src/main/java/corecord/dev/domain/token/dto/response/TokenResponse.java
  src/main/java/corecord/dev/domain/token/service/TokenService.java
  src/main/java/corecord/dev/domain/user/controller/UserController.java
  src/main/java/corecord/dev/domain/user/converter/UserConverter.java
  src/main/java/corecord/dev/domain/user/dto/response/UserResponse.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Refactor ♻️

#66 [Feat/#47] 경험 기록 리스트 조회 페이징 처리 구현
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/record/controller/RecordController.java
  src/main/java/corecord/dev/domain/record/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/dto/response/RecordResponse.java
  src/main/java/corecord/dev/domain/record/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Feat 💙

#68 [Refactor/#67] : Authorization 헤더 검사 로직 추가
  src/main/java/corecord/dev/common/config/SecurityConfig.java
  src/main/java/corecord/dev/common/util/JwtFilter.java
  src/main/java/corecord/dev/domain/chat/service/SummaryService.java
Labels: Refactor ♻️

#72 [Refactor/#69] 로그인 실패 핸들러 구현
  src/main/java/corecord/dev/common/config/CustomAccessDeniedHandler.java
  src/main/java/corecord/dev/common/config/SecurityConfig.java
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/common/util/JwtFilter.java
  src/main/java/corecord/dev/common/util/JwtUtil.java
  src/main/java/corecord/dev/domain/auth/constant/TokenSuccessStatus.java
  src/main/java/corecord/dev/domain/auth/controller/TokenController.java
  src/main/java/corecord/dev/domain/auth/entity/RefreshToken.java
  src/main/java/corecord/dev/domain/auth/entity/TmpToken.java
  src/main/java/corecord/dev/domain/auth/exception/enums/TokenErrorStatus.java
  src/main/java/corecord/dev/domain/auth/exception/model/TokenException.java
  src/main/java/corecord/dev/domain/auth/handler/OAuthLoginFailureHandler.java
  src/main/java/corecord/dev/domain/auth/handler/OAuthLoginSuccessHandler.java
  src/main/java/corecord/dev/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/corecord/dev/domain/auth/repository/TmpTokenRepository.java
  src/main/java/corecord/dev/domain/auth/service/TokenService.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Refactor ♻️

#75 [Refactor/#73] 메모 요약, 역량 분석 기능 AI 변경
  .gitignore
  build.gradle
  src/main/java/corecord/dev/common/config/OpenAIConfig.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/analysis/service/OpenAiService.java
  src/main/java/corecord/dev/domain/chat/service/ChatService.java
  src/main/java/corecord/dev/domain/chat/service/ClovaRequest.java
  src/main/java/corecord/dev/domain/chat/service/ClovaService.java
Labels: Refactor ♻️

#78 [Refactor/#77] 예외 처리 추가
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/common/response/ApiResponse.java
  src/main/java/corecord/dev/common/status/ErrorStatus.java
  src/main/java/corecord/dev/domain/analysis/controller/AnalysisController.java
  src/main/java/corecord/dev/domain/chat/controller/ChatController.java
  src/main/java/corecord/dev/domain/chat/dto/request/ChatRequest.java
  src/main/java/corecord/dev/domain/chat/dto/request/ChatSummaryRequest.java
  src/main/java/corecord/dev/domain/folder/controller/FolderController.java
  src/main/java/corecord/dev/domain/record/controller/RecordController.java
  src/main/java/corecord/dev/domain/user/dto/request/UserRequest.java
Labels: Refactor ♻️

#81 [Refactor/#70] 회원 탈퇴 기능 쿼리 개선
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisResponse.java
  src/main/java/corecord/dev/domain/analysis/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/repository/AnalysisRepository.java
  src/main/java/corecord/dev/domain/folder/repository/FolderRepository.java
  src/main/java/corecord/dev/domain/record/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/user/entity/User.java
  src/main/java/corecord/dev/domain/user/repository/UserRepository.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Refactor ♻️

#85 [Refactor/#84] Ability, Analysis 도메인 분리
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/domain/ability/constant/AbilitySuccessStatus.java
  src/main/java/corecord/dev/domain/ability/controller/AbilityController.java
  src/main/java/corecord/dev/domain/ability/converter/AbilityConverter.java
  src/main/java/corecord/dev/domain/ability/dto/response/AbilityResponse.java
  src/main/java/corecord/dev/domain/ability/entity/Ability.java
  src/main/java/corecord/dev/domain/ability/entity/Keyword.java
  src/main/java/corecord/dev/domain/ability/exception/enums/AbilityErrorStatus.java
  src/main/java/corecord/dev/domain/ability/exception/model/AbilityException.java
  src/main/java/corecord/dev/domain/ability/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/ability/service/AbilityService.java
  src/main/java/corecord/dev/domain/analysis/constant/AnalysisSuccessStatus.java
  src/main/java/corecord/dev/domain/analysis/controller/AnalysisController.java
  src/main/java/corecord/dev/domain/analysis/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisResponse.java
  src/main/java/corecord/dev/domain/analysis/entity/Analysis.java
  src/main/java/corecord/dev/domain/analysis/exception/enums/AnalysisErrorStatus.java
  src/main/java/corecord/dev/domain/analysis/repository/AnalysisRepository.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/chat/service/ChatService.java
  src/main/java/corecord/dev/domain/record/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
  src/main/java/corecord/dev/domain/user/entity/User.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Refactor ♻️

#88 [Test/#82] JwtUtil, User 관련 테스트 코드 추가
  src/main/java/corecord/dev/common/config/SecurityConfig.java
  src/main/java/corecord/dev/domain/auth/handler/OAuthLoginSuccessHandler.java
  src/main/java/corecord/dev/domain/auth/service/TokenService.java
  src/main/java/corecord/dev/domain/auth/util/JwtFilter.java
  src/main/java/corecord/dev/domain/auth/util/JwtUtil.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
  src/test/java/corecord/dev/auth/util/JwtUtilTest.java
  src/test/java/corecord/dev/user/repository/UserRepositoryTest.java
  src/test/java/corecord/dev/user/service/UserServiceTest.java
Labels: Test 🧪

#92 [Chore/#90] 경험 기록 리스트 반환 개수 수정 & 메모 임시 저장 내역 조회 오류 해결
  src/main/java/corecord/dev/domain/ability/service/AbilityService.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Chore 🧹, Fix 🛠️

#91 [Test/#83] 채팅 테스트 코드 추가
  src/main/java/corecord/dev/domain/chat/dto/request/ChatRequest.java
  src/test/java/corecord/dev/chat/repository/ChatRepositoryTest.java
  src/test/java/corecord/dev/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/corecord/dev/chat/service/ChatServiceTest.java
Labels: Test 🧪

#96 [Test/#94] Analysis, Ability 도메인 관련 테스트 코드 작성
  src/main/java/corecord/dev/domain/ability/exception/enums/AbilityErrorStatus.java
  src/main/java/corecord/dev/domain/ability/service/AbilityService.java
  src/main/java/corecord/dev/domain/analysis/dto/request/AnalysisRequest.java
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisAiResponse.java
  src/main/java/corecord/dev/domain/analysis/exception/enums/AnalysisErrorStatus.java
  src/test/java/corecord/dev/ability/service/AbilityServiceTest.java
  src/test/java/corecord/dev/analysis/service/AnalysisServiceTest.java
Labels: Test 🧪

#100 [Refactor/#99] : 외부 API 와 DB 호출 서비스 분리
  src/main/java/corecord/dev/domain/chat/application/ChatDbService.java
  src/main/java/corecord/dev/domain/chat/application/ChatService.java
  src/main/java/corecord/dev/domain/folder/domain/dto/request/FolderRequest.java
  src/test/java/corecord/dev/chat/service/ChatServiceTest.java
Labels: Refactor ♻️

#102 [Chore/#101] 역량 분석 상세 조회 Response 수정
  src/main/java/corecord/dev/domain/analysis/domain/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/domain/dto/request/AnalysisRequest.java
  src/main/java/corecord/dev/domain/analysis/domain/dto/response/AnalysisResponse.java
  src/main/java/corecord/dev/domain/analysis/domain/repository/AnalysisRepository.java
Labels: Chore 🧹

#107 [Refactor/#103] 외부 API 호출 Transaction 분리 & 도메인별 DBService 생성
  src/main/java/corecord/dev/domain/ability/application/AbilityDbService.java
  src/main/java/corecord/dev/domain/ability/application/AbilityService.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisDbService.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisService.java
  src/main/java/corecord/dev/domain/chat/application/ChatDbService.java
  src/main/java/corecord/dev/domain/chat/application/ChatService.java
  src/main/java/corecord/dev/domain/folder/application/FolderDbService.java
  src/main/java/corecord/dev/domain/folder/application/FolderService.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/application/RecordService.java
  src/main/java/corecord/dev/domain/user/application/UserDbService.java
  src/main/java/corecord/dev/domain/user/application/UserService.java
  src/test/java/corecord/dev/ability/service/AbilityServiceTest.java
  src/test/java/corecord/dev/chat/service/ChatServiceTest.java
Labels: Refactor ♻️

#108 [Refactor/#104] : 테이블명 및 컬럼명 명시적으로 작성
  src/main/java/corecord/dev/domain/ability/domain/entity/Ability.java
  src/main/java/corecord/dev/domain/analysis/domain/entity/Analysis.java
  src/main/java/corecord/dev/domain/chat/domain/entity/Chat.java
  src/main/java/corecord/dev/domain/chat/domain/entity/ChatRoom.java
  src/main/java/corecord/dev/domain/folder/domain/entity/Folder.java
  src/main/java/corecord/dev/domain/record/domain/entity/Record.java
  src/main/java/corecord/dev/domain/user/domain/entity/User.java
Labels: Refactor ♻️

#109 [Refactor/#105] : 채팅 AI 인터페이스 분리
  src/main/java/corecord/dev/common/status/ErrorStatus.java
  src/main/java/corecord/dev/domain/chat/application/ChatAIService.java
  src/main/java/corecord/dev/domain/chat/application/ChatService.java
  src/main/java/corecord/dev/domain/chat/domain/converter/ChatConverter.java
  src/main/java/corecord/dev/domain/chat/domain/dto/response/ChatSummaryAiResponse.java
  src/main/java/corecord/dev/domain/chat/infra/clova/application/ClovaService.java
  src/main/java/corecord/dev/domain/chat/infra/openai/application/OpenAiChatService.java
  src/main/java/corecord/dev/domain/chat/status/ChatErrorStatus.java
  src/test/java/corecord/dev/chat/service/ChatServiceTest.java
Labels: Refactor ♻️

#111 [Chore/#110] 경험 기록 내용이 충분하지 않을 시 Error 반환
  src/main/java/corecord/dev/domain/analysis/application/AnalysisService.java
  src/main/java/corecord/dev/domain/record/application/RecordService.java
  src/main/java/corecord/dev/domain/record/status/RecordErrorStatus.java
Labels: Chore 🧹

#113 [Fix/#112] 폴더명 중복 검사 수정
  src/main/java/corecord/dev/domain/folder/application/FolderDbService.java
  src/main/java/corecord/dev/domain/folder/application/FolderService.java
  src/main/java/corecord/dev/domain/folder/domain/repository/FolderRepository.java
Labels: Fix 🛠️

#115 [Refactor/#114] : 컨트롤러에서 HTTP 레이어 객체 처리
  src/main/java/corecord/dev/common/auth/TokenCookieManager.java
  src/main/java/corecord/dev/common/util/CookieUtil.java
  src/main/java/corecord/dev/domain/auth/application/TokenService.java
  src/main/java/corecord/dev/domain/auth/presentation/TokenController.java
  src/main/java/corecord/dev/domain/user/application/UserService.java
  src/main/java/corecord/dev/domain/user/domain/converter/UserConverter.java
  src/main/java/corecord/dev/domain/user/domain/dto/response/UserResponse.java
  src/main/java/corecord/dev/domain/user/presentation/UserController.java
  src/test/java/corecord/dev/user/service/UserServiceTest.java
Labels: Refactor ♻️

#116 [Refactor/#106] 폴더 삭제 기능 쿼리 개선
  src/main/java/corecord/dev/domain/ability/application/AbilityDbService.java
  src/main/java/corecord/dev/domain/ability/domain/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisDbService.java
  src/main/java/corecord/dev/domain/analysis/domain/repository/AnalysisRepository.java
  src/main/java/corecord/dev/domain/chat/application/ChatDbService.java
  src/main/java/corecord/dev/domain/chat/domain/repository/ChatRepository.java
  src/main/java/corecord/dev/domain/chat/domain/repository/ChatRoomRepository.java
  src/main/java/corecord/dev/domain/folder/application/FolderService.java
  src/main/java/corecord/dev/domain/folder/domain/repository/FolderRepository.java
  src/main/java/corecord/dev/domain/record/application/RecordDbService.java
  src/main/java/corecord/dev/domain/record/domain/repository/RecordRepository.java
Labels: Refactor ♻️

#118 [Test/#117] 서비스 단위 테스트 수정
  src/test/java/corecord/dev/analysis/service/AnalysisServiceTest.java
  src/test/java/corecord/dev/folder/repository/FolderRepositoryTest.java
  src/test/java/corecord/dev/folder/service/FolderServiceTest.java
  src/test/java/corecord/dev/record/memo/service/MemoRecordServiceTest.java
Labels: Test 🧪

#120 [Refactor/#119] 함수 나열 위치 변경
  src/main/java/corecord/dev/domain/ability/application/AbilityService.java
  src/main/java/corecord/dev/domain/analysis/application/AnalysisService.java
  src/main/java/corecord/dev/domain/chat/application/ChatService.java
  src/main/java/corecord/dev/domain/folder/application/FolderService.java
  src/main/java/corecord/dev/domain/record/application/RecordService.java
  src/main/java/corecord/dev/domain/record/status/RecordErrorStatus.java
  src/main/java/corecord/dev/domain/user/application/UserService.java
Labels: Refactor ♻️

#122 [Refactor/#121] : 쿠키 보안 요소 SameSite 배포용으로 변경
  src/main/java/corecord/dev/common/util/CookieUtil.java
Labels: Refactor ♻️
