Repository KUSITMS-MOAMOA/MOAMOA_BE, pull requests merged in 2024-10, with the labels that each got.

#2 [Add/#1] Common 파일 추가 및 Domain 폴더링
  build.gradle
  src/main/java/corecord/dev/common/base/BaseEntity.java
  src/main/java/corecord/dev/common/config/SwaggerConfig.java
  src/main/java/corecord/dev/common/exception/GeneralException.java
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/common/response/ApiResponse.java
  src/main/java/corecord/dev/common/status/ErrorStatus.java
  src/main/java/corecord/dev/common/status/SuccessStatus.java
  src/main/java/corecord/dev/domain/controller/UserController.java
  src/main/java/corecord/dev/domain/converter/UserConverter.java
  src/main/java/corecord/dev/domain/dto/request/UserRequest.java
  src/main/java/corecord/dev/domain/dto/response/UserResponse.java
  src/main/java/corecord/dev/domain/entity/User.java
  src/main/java/corecord/dev/domain/repository/UserRepository.java
  src/main/java/corecord/dev/domain/service/UserService.java
Labels: Add ✨

#6 [Add/#5] : HealthCheckController 추가
  src/main/java/corecord/dev/HealthCheckController.java
Labels: Add ✨

#8 [Add/#7]: yml 파일 설정
  .gitignore
  build.gradle
  src/main/resources/application.yml
Labels: Add ✨

#14 [Add/#12] 로그인 방식 수정
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/common/status/ErrorStatus.java
  src/main/java/corecord/dev/common/util/CookieUtil.java
  src/main/java/corecord/dev/common/util/JwtFilter.java
  src/main/java/corecord/dev/common/util/JwtUtil.java
  src/main/java/corecord/dev/domain/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/corecord/dev/domain/token/converter/TokenConverter.java
  src/main/java/corecord/dev/domain/token/exception/enums/TokenErrorStatus.java
  src/main/java/corecord/dev/domain/token/service/TokenService.java
  src/main/java/corecord/dev/domain/user/controller/UserController.java
  src/main/java/corecord/dev/domain/user/converter/UserConverter.java
  src/main/java/corecord/dev/domain/user/entity/Status.java
  src/main/java/corecord/dev/domain/user/entity/User.java
  src/main/java/corecord/dev/domain/user/exception/enums/UserErrorStatus.java
  src/main/java/corecord/dev/domain/user/exception/model/UserException.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Add ✨

#15 [Add/#9] Entity간 연관관계 설정
  src/main/java/corecord/dev/domain/analysis/constant/Keyword.java
  src/main/java/corecord/dev/domain/analysis/entity/Ability.java
  src/main/java/corecord/dev/domain/analysis/entity/Analysis.java
  src/main/java/corecord/dev/domain/chat/entity/Chat.java
  src/main/java/corecord/dev/domain/chat/entity/ChatRoom.java
  src/main/java/corecord/dev/domain/folder/entity/Folder.java
  src/main/java/corecord/dev/domain/record/constant/RecordType.java
  src/main/java/corecord/dev/domain/record/entity/Record.java
  src/main/java/corecord/dev/domain/user/entity/User.java
Labels: Add ✨

#19 [Fix/#18] 로그인 관련 쿠키 도입 및 임시 토큰 발급 로직 추가
  src/main/java/corecord/dev/common/util/CookieUtil.java
  src/main/java/corecord/dev/common/util/JwtUtil.java
  src/main/java/corecord/dev/domain/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/corecord/dev/domain/token/constant/TokenSuccessStatus.java
  src/main/java/corecord/dev/domain/token/controller/TokenController.java
  src/main/java/corecord/dev/domain/token/entity/TmpToken.java
  src/main/java/corecord/dev/domain/token/exception/enums/TokenErrorStatus.java
  src/main/java/corecord/dev/domain/token/repository/RefreshTokenRepository.java
  src/main/java/corecord/dev/domain/token/repository/TmpTokenRepository.java
  src/main/java/corecord/dev/domain/token/service/TokenService.java
  src/main/java/corecord/dev/domain/user/controller/UserController.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Refactor ♻️, Fix 🛠️

#20 [Feat/#11] 마이페이지 기능 구현
  src/main/java/corecord/dev/common/util/CookieUtil.java
  src/main/java/corecord/dev/domain/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/corecord/dev/domain/record/entity/Record.java
  src/main/java/corecord/dev/domain/user/constant/UserSuccessStatus.java
  src/main/java/corecord/dev/domain/user/controller/UserController.java
  src/main/java/corecord/dev/domain/user/converter/UserConverter.java
  src/main/java/corecord/dev/domain/user/dto/request/UserRequest.java
  src/main/java/corecord/dev/domain/user/dto/response/UserResponse.java
  src/main/java/corecord/dev/domain/user/entity/User.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Feat 💙

#22 [Chore/#21] Folder-User Mapping
  src/main/java/corecord/dev/domain/folder/constant/FolderSuccessStatus.java
  src/main/java/corecord/dev/domain/folder/controller/FolderController.java
  src/main/java/corecord/dev/domain/folder/converter/FolderConverter.java
  src/main/java/corecord/dev/domain/folder/dto/request/FolderRequest.java
  src/main/java/corecord/dev/domain/folder/entity/Folder.java
  src/main/java/corecord/dev/domain/folder/exception/enums/FolderErrorStatus.java
  src/main/java/corecord/dev/domain/folder/repository/FolderRepository.java
  src/main/java/corecord/dev/domain/folder/service/FolderService.java
  src/main/java/corecord/dev/domain/user/entity/User.java
Labels: Chore 🧹

#28 [Fix/#27] : 인증되지 않은 User 에러 반환 수정
  src/main/java/corecord/dev/common/config/SecurityConfig.java
Labels: Fix 🛠️

#29 [Fix/#26] : 중복 회원가입 방지 코드 추가
  src/main/java/corecord/dev/domain/user/exception/enums/UserErrorStatus.java
  src/main/java/corecord/dev/domain/user/repository/UserRepository.java
  src/main/java/corecord/dev/domain/user/service/UserService.java
Labels: Fix 🛠️

#30 [Feat/#24] MEMO ver. 경험 기록 임시 저장 기능 구현
  src/main/java/corecord/dev/domain/record/constant/RecordSuccessStatus.java
  src/main/java/corecord/dev/domain/record/controller/RecordController.java
  src/main/java/corecord/dev/domain/record/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/dto/request/RecordRequest.java
  src/main/java/corecord/dev/domain/record/dto/response/RecordResponse.java
  src/main/java/corecord/dev/domain/record/exception/enums/RecordErrorStatus.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
  src/main/java/corecord/dev/domain/user/entity/User.java
Labels: Feat 💙

#32 [Feat/#25] 역량 분석 기능 구현(1)
  src/main/java/corecord/dev/common/base/BaseEntity.java
  src/main/java/corecord/dev/common/exception/GeneralExceptionAdvice.java
  src/main/java/corecord/dev/domain/analysis/constant/AnalysisSuccessStatus.java
  src/main/java/corecord/dev/domain/analysis/constant/Keyword.java
  src/main/java/corecord/dev/domain/analysis/controller/AnalysisController.java
  src/main/java/corecord/dev/domain/analysis/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/dto/request/AnalysisRequest.java
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisResponse.java
  src/main/java/corecord/dev/domain/analysis/entity/Ability.java
  src/main/java/corecord/dev/domain/analysis/entity/Analysis.java
  src/main/java/corecord/dev/domain/analysis/exception/enums/AnalysisErrorStatus.java
  src/main/java/corecord/dev/domain/analysis/exception/model/AnalysisException.java
  src/main/java/corecord/dev/domain/analysis/repository/AbilityRepository.java
  src/main/java/corecord/dev/domain/analysis/repository/AnalysisRepository.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/record/entity/Record.java
  src/main/java/corecord/dev/domain/record/exception/enums/RecordErrorStatus.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Feat 💙

#33 [Feat/#31] 경험 기록 리스트 조회 기능 구현
  src/main/java/corecord/dev/domain/analysis/entity/Ability.java
  src/main/java/corecord/dev/domain/analysis/entity/Analysis.java
  src/main/java/corecord/dev/domain/folder/repository/FolderRepository.java
  src/main/java/corecord/dev/domain/record/constant/RecordSuccessStatus.java
  src/main/java/corecord/dev/domain/record/controller/RecordController.java
  src/main/java/corecord/dev/domain/record/converter/RecordConverter.java
  src/main/java/corecord/dev/domain/record/dto/response/RecordResponse.java
  src/main/java/corecord/dev/domain/record/entity/Record.java
  src/main/java/corecord/dev/domain/record/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Feat 💙

#36 [Feat/#35] 역량 키워드 리스트 조회 기능 구현
  src/main/java/corecord/dev/domain/analysis/constant/AnalysisSuccessStatus.java
  src/main/java/corecord/dev/domain/analysis/controller/AnalysisController.java
  src/main/java/corecord/dev/domain/analysis/converter/AnalysisConverter.java
  src/main/java/corecord/dev/domain/analysis/dto/response/AnalysisResponse.java
  src/main/java/corecord/dev/domain/analysis/repository/AnalysisRepository.java
  src/main/java/corecord/dev/domain/analysis/service/AnalysisService.java
  src/main/java/corecord/dev/domain/record/repository/RecordRepository.java
  src/main/java/corecord/dev/domain/record/service/RecordService.java
Labels: Feat 💙
